// <auto-generated />
using System;
using Folders.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Folders.DB.Migrations
{
    [DbContext(typeof(FoldersContext))]
    [Migration("20190906123204_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Folders.DB.Models.Folder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<long?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Resources",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Primary Sources",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Secondary Sources",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Evidence",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Graphic Products",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Process",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Final Product",
                            ParentId = 6L
                        });
                });

            modelBuilder.Entity("Folders.DB.Models.RootFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("RootId");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.ToTable("Roots");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            RootId = 1L
                        });
                });

            modelBuilder.Entity("Folders.DB.Models.Folder", b =>
                {
                    b.HasOne("Folders.DB.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Folders.DB.Models.RootFolder", b =>
                {
                    b.HasOne("Folders.DB.Models.Folder", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
